### ISSUE TITLE
CASFRI Documentation workflow section

### ISSUE THREAD

**Issue by MelinaHoule** [CASFRI/PostgreSQL-Table-Translation-Framework#175]
In the CASFRI documentation, in the Workflow section, subsection Translation, the first item is "Validate dependency tables using the loaded validation tables". How that action should be performed? More details are needed. 

Also, on the second item "Run the translation engine....", it is not clear where to stop in the "PostgreSQL-Table-Translation-Framework" documentation. If the action is only to install the helperFunctions, we should clarify the procedure in the CASFRI workflow. Also I didn't see when helperFunctionsCASFRI needed to be loaded. Should it be mentionned in the CASFRI workflow or is it later that step occurs?

**Comment by pedrogit** [comment]
I think those issues have been adressed when revising the documentation. Closing.
